import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@bootcamp/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

function Home() {

  const games: {id: string; title: string;}[] = [
    {id: '1aa60994-c480-452e-a281-0fbaa6379e9f', title: 'Summoners War: Chronicles'},
    {id: '0b1da382-5dff-4916-9c44-a44e7cbd79b3', title: 'World Boss'},
    {id: 'f35cdeac-c42e-4af1-a414-71f2a876ca44', title: 'Marvel Snap'},
    {id: '13bdc174-6d0e-45cb-8611-06bf9dcdf927', title: 'Overwatch 2'},
    {id: 'f1b6517a-a46e-451d-99a6-97bc55094386', title: 'Deathverse: Let It Die'},
    {id: '7d06eaff-c81a-474c-b0e7-630103b5dbf1', title: 'Gundam Evolution'},
    {id: '67f34b05-7c87-4e7f-8411-e1b2ed6a1fda', title: 'Omega Strikers'},
    {id: '8ef3b86d-27aa-4d69-b214-0d3262b036a2', title: 'Galahad 3093'},
    {id: '98a9c25a-a005-4cc3-bb0e-b74a7b8136b6', title: 'A.V.A Global'},
  ]
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <ul>
            {games.map(game => (
            <li key={game.id}>{game.title}</li>
            ))}
          </ul>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}

export default Home;